Added html for picture in recipe
KamilKrauze/agile_project pull request #44
Opened 2023-01-26 10:39 UTC by gatillom

Added html for picture in recipe, PHP to follow

2023-01-26 12:38 UTC, monberin submitted a review, later dismissed

2023-01-27 17:42 UTC, monberin requested changes
check out how it's done with recipe IDs in ```php_templates/recipe-row.php```

2023-02-02 16:21 UTC, last-genius approved these changes

2023-02-02 16:25 UTC, monberin approved these changes

2023-02-02 16:26 UTC, merged